### PR TITLE
feat(core): rule to fix affect -> effect

### LINKED ISSUE #676: feat: Flag mixing up "affect" (verb) and "effect" (usually noun)
## Description

People commonly mix up "affect" and "effect".
"Affect" is always a verb, meaning to act on a thing or make it change in some way.
"Effect" is usually a noun, meaning a result or consequence of something happening.

But "effect" is less commonly also a verb with a very different meaning, to bring into existence.

## Resources

- [dictionary.com](https://www.dictionary.com/e/affect-vs-effect/)
- [Merriam-Webster](https://www.merriam-webster.com/grammar/affect-vs-effect-usage-difference)
- [Grammarly](https://www.grammarly.com/blog/commonly-confused-words/affect-vs-effect/)

## Examples

- Variable not **effecting** triggers or Button Feeback
- but I still want to **effect** parent's check situation
- Change in ElementQuery::count **effecting** EVENT_BEFORE_PREPARE events
- experimentalUseProvidedRuntime not **effected** when running "npm run deploy"
- panel class doesn't seem to have an **affect**
- the IP version switch does not have an **affect**
- New line creates space between text when that is not always the **affect**

### PR DESCRIPTION
**Pull request by elijah-potter**
# Issues 

Closes #676 

# Description

Adds a linter for accidental swapping of `affect` for `effect` and vice versa. It was produced with a combination of [evolution](https://elijahpotter.dev/articles/harper_evolves) and LLM-assisted codegen. It may have problems as a result. 

# How Has This Been Tested?

Many additional unit tests.

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have added tests to cover my changes

### CODE REVIEW

**Comment by hippietrail** [comment]
Check if this handles the cases in `linting/noun_verb_confusion/mod.rs` and `linting/noun_verb_confusion/verb_instead_of_noun.rs` too and decide if they can be removed or put together in a `lint_group` etc.

File: harper-core/src/linting/effect_affect/affect_to_effect.rs [hunk 1]
```diff
@@ -78,27 +78,25 @@ impl ExprLinter for AffectToEffect {
...
-                if !matches!(
-                    lower_prev.as_str(),
-                    "take" | "takes" | "taking" | "took" | "taken"
-                ) {
-                    return None;
-                }
+        if let Some(prev) = preceding
+            && (prev.kind.is_upos(UPOS::AUX) || prev.kind.is_upos(UPOS::VERB))
+        {
+            let lower_prev = prev.span.get_content_string(source).to_lowercase();
```
Comment (hippietrail) [inline harper-core/src/linting/effect_affect/affect_to_effect.rs]: Oh you'll be able to change this to work without an allocation by using `.get_content()` with `.eq_ignore_ascii_case_str()` or `.eq_any_ignore_ascii_case_chars()`

Comment (elijah-potter) [reply harper-core/src/linting/effect_affect/affect_to_effect.rs]: Yup. Silly LLMs
