### PR TITLE
fix(chrome-ext): Draft.js multiline suggestion replacement corruption

### LINKED ISSUE #2596: Applying suggestion on Draft.js corrupts text on other lines
**Describe the bug**
When using Harper on a Draft.js editor with multiple lines, applying a suggestion on one line corrupts text on other lines (where the cursor is positioned).

**To Reproduce**
1. Go to x.com and start composing a new post
2. Type multiline text with errors: "The first tset." then Enter, "The second tset." then Enter, "The third tset."
3. Click on the Harper highlight for the second line's "tset" while the cursor is on the end of third line.
4. Click "Replace with test"

**Expected behaviour**
Only the second "tset" is corrected. Other lines remain unchanged.

**Actual behaviour**
Text on other lines gets corrupted or duplicated.

**Platform**
Browser: Brave (Chromium-based)
Editor: X post composer (Draft.js)

**Additional context**
Issue appears specific to Draft.js editors. Slate, Lexical, and ProseMirror work correctly.

### PR DESCRIPTION
**Pull request by draphy**
# Issues
Fixes #2596

# Description
When applying a Harper suggestion in Draft.js editors (like X/Twitter post composer), text on other lines would get corrupted if the cursor was positioned on a different line than the suggestion being applied.

The fix adds a dedicated `replaceDraftValue()` handler that uses `setTimeout(0)` to defer the DOM replacement, allowing Draft.js's internal state to settle before making changes.

# How Has This Been Tested?
- Added `testMultipleSuggestionsAndUndo` test for Draft.js, Slate, Lexical, and ProseMirror
- Tests verify that applying a suggestion on one line doesn't corrupt other lines
- All 4 editor tests pass

# Checklist
- [x] I have performed a self-review of my own code
- [x] I have added tests to cover my changes

### CODE REVIEW

File: packages/chrome-plugin/tests/testUtils.ts [hunk 1]
```diff
@@ -171,17 +181,81 @@ export async function testCanBlockRuleTextareaSuggestion(testPageUrl: TestPageUr
...
+		}
+	}
+
+	boxes.sort((a, b) => (Math.abs(a.y - b.y) > 5 ? a.y - b.y : a.x - b.x));
+
+	return boxes;
+}
+
+/** Test multiline suggestion replacement and undo. */
+export async function testMultipleSuggestionsAndUndo(
```
Comment (elijah-potter) [inline packages/chrome-plugin/tests/testUtils.ts:203]: I like this structure.

File: packages/chrome-plugin/tests/slate.spec.ts [hunk 2]
```diff
@@ -22,21 +23,23 @@ test('Can apply basic suggestion.', async ({ page }) => {
...
 	await slate.press('ArrowLeft');
 	await slate.press('ArrowLeft');
 	await slate.press('Backspace');
-	expect(slate).toContainText('This is a tst');
+	await expect(slate).toContainText('This is a tst');
 
 	// Verify typing still works.
 	await slate.pressSequentially('e');
-	expect(slate).toContainText('This is a test');
+	await expect(slate).toContainText('This is a test');
```
Comment (elijah-potter) [inline packages/chrome-plugin/tests/slate.spec.ts:38]: Have we been missing these `await`s this whole time? If so, that's embarrassing for me.

File: packages/lint-framework/src/lint/computeLintBoxes.ts [hunk 3]
```diff
@@ -129,6 +131,33 @@ function replaceLexicalValue(
 	el.dispatchEvent(new InputEvent('input', { bubbles: true, cancelable: false }));
 }
 
+function replaceDraftValue(
```
Comment (elijah-potter) [inline packages/lint-framework/src/lint/computeLintBoxes.ts:134]: Good stuff.

File: packages/chrome-plugin/tests/slate.spec.ts (hunk 2 above)
Comment (draphy) [reply packages/chrome-plugin/tests/slate.spec.ts:38]: Yeah, we didn't have those before and it was likely causing some flaky test failures.
