### PR TITLE
fix(core): the Oxford comma applies to `nor` as well

### LINKED ISSUE #420: Oxford comma, aka Serial comma with "nor"
Oxford comma not only applies for `and` and `or`, but also for `nor`

https://www.umaryland.edu/media/umb/oaa/campus-life/writing-center/documents/Commas.pdf

### PR DESCRIPTION
**Pull request by elijah-potter**
Resolves #420

### CODE REVIEW

File: harper-core/src/linting/oxford_comma.rs [hunk 1]
```diff
@@ -150,4 +150,13 @@ mod tests {
             "They enjoy playing soccer, basketball, or tennis.",
         );
     }
+
+    #[test]
+    fn nor_vegetables() {
+        assert_suggestion_result(
+            "I like carrots, kale nor broccoli.",
+            OxfordComma::default(),
+            "I like carrots, kale, nor broccoli.",
```
Comment (ccoVeille) [inline harper-core/src/linting/oxford_comma.rs:159]: this example seems to come out your childhood 🤣

File: harper-core/src/linting/oxford_comma.rs [hunk 2]
```diff
@@ -21,7 +21,7 @@ impl OxfordComma {
                 ))
                 .then_noun_phrase()
                 .then_whitespace()
-                .then(Box::new(WordSet::all(&["and", "or"])))
+                .then(Box::new(WordSet::all(&["and", "or", "nor"])))
```
Comment (ccoVeille) [inline harper-core/src/linting/oxford_comma.rs:24]: The description function around line 80 also need to be updated.

And I like the fact you will have to use an Oxford list to write it 😁

File: harper-core/src/linting/oxford_comma.rs (hunk 1 above)
Comment (grantlemons) [inline harper-core/src/linting/oxford_comma.rs:159]: I feel like these should have neither at the beginning, but it's gramatically correct as is.

Comment (elijah-potter) [reply harper-core/src/linting/oxford_comma.rs:159]: It does. I still don't like broccoli.

**Review by ccoVeille — APPROVED** [review]

**Comment by ccoVeille** [comment]
About https://github.com/Automattic/harper/commit/458566126d5e5d0b1cd2d2b95de5bd6f92f19432, I would like to suggest using co-authored-by tag 😁
