### PR TITLE
fix(chrome-ext): Applying suggestions breaks cursor/keyboard in Draft.js and Slate editors

### LINKED ISSUE #2470: Text input breaks after accepting Harper suggestion in Discord on Brave
**Describe the bug**
After accepting a Harper suggestion while writing a Discord message, the backspace and left/right arrow keys become unresponsive. Additional characters can be written, and the up/down arrow keys function normally, but the issue remains. The issue can be resolved by briefly switching to another Discord page (another channel, server, DM, etc.), but the text written after the Harper suggestion was accepted is missing.

**To Reproduce**
1. Write a Discord message with a grammatical error.
2. Click on the text highlighted by Harper.
3. Click on one of the suggestions in the resulting Harper pop-up.
4. Attempt to delete text or move the text cursor using the arrow keys.
5. Click on another Discord channel, server, or DM.
6. Return to the original Discord page with the message (some text is now missing).

**Expected behavior**
Step 4 should allow the user to delete text and move the text cursor freely. Step 6 should not have any missing text.

**Screenshots**
https://github.com/user-attachments/assets/8de4e8e5-ddb9-4670-86c3-823fc38e4a07

**Platform**
OS: MacOS 26.2 (Apple Silicon)
Brave Browser Version: 1.82.173
Chromium Version: 140.0.7339.213
Harper Version: 1.4.1
Website: Discord

**Additional context**
None

### LINKED ISSUE #2494: Applying suggestions in Draft.js editors (X/Twitter) breaks cursor and keyboard input
**Describe the bug**
On X/Twitter, clicking a Harper suggestion fixes the text but cursor jumps to position 0 and backspace stops working.

**To Reproduce**
1. Go to X/Twitter and start composing a post
2. Type a grammar error (e.g., "Take a look to the code")
3. Click Harper's suggestion to fix it
4. Cursor jumps to beginning, backspace doesn't work

**Expected behavior**
Cursor stays near corrected word, keyboard continues working normally for backspace.

**Platform**
Chrome extension - any Draft.js editor (X/Twitter, Facebook)

**Root cause**
Draft.js maintains internal state separate from DOM. Direct `el.textContent` manipulation breaks state sync.

### PR DESCRIPTION
**Pull request by draphy**
# Issues 
Fixes #2494
Fixes #2470

# Description
Applying suggestions in Draft.js (X/Twitter) and Slate (Discord) editors broke keyboard input.

**Fix:** Use surgical text replacement with `execCommand` that editors can observe and sync their internal state.

# How Has This Been Tested?
- Manually tested on X/Twitter and Discord web
- Added integration tests for Draft.js and Slate verifying arrow keys and backspace work after applying suggestions

# Checklist
- [x] I have performed a self-review of my own code
- [x] I have added tests to cover my changes

### CODE REVIEW

**Comment by elijah-potter** [comment]
This looks great! I'm tempted to just hit merge now.

Before I can do that, I would like to know: Did you end up having a go at writing an integration test to make sure it now works as expected on Draft.js? If not, that's totally fine, but I would like to know if you encountered any snags.

I'm curious if this PR has the potential to address #2470.

**Comment by draphy** [comment]
> This looks great! I'm tempted to just hit merge now.
> 
> Before I can do that, I would like to know: Did you end up having a go at writing an integration test to make sure it now works as expected on Draft.js? If not, that's totally fine, but I would like to know if you encountered any snags.
> 
> I'm curious if this PR has the potential to address #2470.

Was planning to add integration tests. Checked the existing ones and some use local mocks, others use live sites (Slate, Lexical). Was initially hesitant about depending on an external live page, but setting up a local Draft.js mock with React felt overly complex. Since you mentioned test, i reconsidered it and going with https://draftjs.org/ seems simpler and consistent with the other editor tests. Tested manually as of now and it works fine. Will push the tests shortly. Let me know if you have any suggestions.

For #2470 - symptoms look identical. I'll check what editor Discord uses and if it's not already fixed by this PR, I'll include the fix here.

**Comment by draphy** [comment]
@elijah-potter PR ready for review

File: packages/lint-framework/src/lint/computeLintBoxes.ts
Comment (elijah-potter) [inline packages/lint-framework/src/lint/computeLintBoxes.ts]: It seems that the `slate` half of this discriminated union is no longer used. Would you mind cleaning that up?

File: packages/lint-framework/src/lint/computeLintBoxes.ts [hunk 1]
```diff
@@ -113,6 +117,72 @@ function replaceRichTextValue(el: HTMLElement, value: string, opts: { mode: 'lex
 	specialInsertText(el, value, opts);
 }
 
+function replaceDraftJsValue(
```
Comment (elijah-potter) [inline packages/lint-framework/src/lint/computeLintBoxes.ts]: Great stuff.

File: packages/chrome-plugin/tests/slate.spec.ts [hunk 2]
```diff
@@ -24,10 +24,17 @@ test('Can apply basic suggestion.', async ({ page }) => {
 
 	expect(slate).toContainText('This is a test');
 
-	// Slate has be known to revert changes after typing some more.
+	// Verify editor state is preserved: arrow keys and backspace must work.
+	// Position cursor before 's' in 'test', then backspace to delete 'e'.
 	await slate.press('End');
-	await slate.pressSequentially(" of Harper's grammar checking.");
-	expect(slate).toContainText("This is a test of Harper's grammar checking.");
+	await slate.press('ArrowLeft');
```
Comment (elijah-potter) [inline packages/chrome-plugin/tests/slate.spec.ts:30]: Awesome.

File: packages/chrome-plugin/tests/draft.spec.ts [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+test('Can apply basic suggestion.', async ({ page }) => {
+	await page.goto(TEST_PAGE_URL);
+
+	const draft = getDraftEditor(page);
+	await draft.scrollIntoViewIfNeeded();
+	await draft.click();
+	await replaceEditorContent(draft, 'This is an test');
+
+	await page.waitForTimeout(3000);
+
```
Comment (elijah-potter) [inline packages/chrome-plugin/tests/draft.spec.ts:21]: Fantastic.

File: packages/vscode-plugin/src/tests/suite/helper.ts [hunk 4]
```diff
@@ -44,7 +44,7 @@ export async function openUntitled(text: string): Promise<Uri> {
 
 export async function setTextDocumentLanguage(uri: Uri, languageId: string): Promise<void> {
 	const document = await workspace.openTextDocument(uri);
-	languages.setTextDocumentLanguage(document, languageId);
+	await languages.setTextDocumentLanguage(document, languageId);
```
Comment (elijah-potter) [inline packages/vscode-plugin/src/tests/suite/helper.ts:47]: Good catch. That must have been an oversight and has likely been contributing to some flaky test failures. Thanks!

Comment (draphy) [reply packages/vscode-plugin/src/tests/suite/helper.ts:47]: Yeah, this was causing a test failure in one of my commit check.

File: packages/lint-framework/src/lint/computeLintBoxes.ts
Comment (draphy) [reply packages/lint-framework/src/lint/computeLintBoxes.ts]: The `'slate'` mode was being used by CKEditor too. Since both Slate and CKEditor can use targeted span replacement, I've unified them to use `replaceSlateValue` directly. Also did some rearrangement like extracted `selectSpanInEditor` as a shared helper and renamed `replaceRichTextValue` to `replaceLexicalValue` for clarity.
