### PR TITLE
fix(#1876): merge dialects from curated, file, user, and workspace dicts

### LINKED ISSUE #1876: Not recognizing "Calibre" or "calibre" even after adding to neovim spell file
**What got flagged?**
Calibre or calibre

**Why is this incorrect?**
Took created by Kovid Goyal and I added it to my spell file

**Example of correct usage:**
See min 8:11 in this video:
https://youtu.be/xTFAbuvcF0A?t=491&si=q_3Vqr1ZSyJUJBat

### PR DESCRIPTION
**Pull request by grantlemons**
# Issues 
Closes #1876

# Description
- Use the `WordMetadata::or` method to combine the metadata of words in `MergedDictionary`
- Add the user's configured dialect to their user, workspace, and file dictionaries in `harper-ls`
- Add test in `harper-core/linters/spell_check.rs`

# How Has This Been Tested?
Created unit test and built and tested on an actual file.

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have added tests to cover my changes

### CODE REVIEW

**Comment by elijah-potter** [comment]
This also solves the issue I've had with the word `Matt`.

File: harper-core/src/spell/dictionary.rs [hunk 1]
```diff
@@ -33,11 +33,11 @@ pub trait Dictionary: Send + Sync {
     ) -> Vec<FuzzyMatchResult<'_>>;
     fn get_correct_capitalization_of(&self, word: &[char]) -> Option<&'_ [char]>;
     /// Get the associated [`WordMetadata`] for any capitalization of a given word.
-    fn get_word_metadata(&self, word: &[char]) -> Option<&WordMetadata>;
```
Comment (elijah-potter) [inline harper-core/src/spell/dictionary.rs:36]: Is this PR possible without changing this? Cloning `WordMetadata` may become more expensive in the near future.

Comment (grantlemons) [reply harper-core/src/spell/dictionary.rs:36]: I don't think so. `Metadata::or` creates a new Metadata object that is owned by `MergedDictionary::get_word_metadata`, so we can't return a reference.

Comment (grantlemons) [reply harper-core/src/spell/dictionary.rs:36]: We could return a `Cow`?

Comment (grantlemons) [reply harper-core/src/spell/dictionary.rs:36]: I changed it to `Cow`

**Review by elijah-potter — APPROVED** [review]
This is a more elegant solution than I could have come up with. Thanks @grantlemons!
