### PR TITLE
fix(chrome-plugin): auto-close report page on tab switch or navigation #3225

### LINKED ISSUE #3225: Close Extension Report Page When Done
The "Report a Problematic Lint" page should automatically close when the user switches to a new site or is otherwise no longer interested in reporting anything.

### PR DESCRIPTION
**Pull request by muhammed-mukthar**
# Issues
Closes #3225

# Description
The "Report a Problematic Lint" popup page was persisting in
`chrome.storage.local` even after the user navigated away or switched
tabs. The next time the popup opened (on any page), it would still
show the report form.

Fix: store the triggering tab ID (`reportTabId`) when the report page
is opened, then add two listeners in the background service worker:
- `chrome.tabs.onActivated` — resets popup state when the user switches
  to a different tab
- `chrome.tabs.onUpdated` — resets popup state when the originating tab
  navigates to a new URL

# Demo
N/A (bug fix — report page no longer re-appears after tab switching or navigation)

# How Has This Been Tested?
Manually: triggered the report page, switched tabs, reopened the popup — 
confirmed it shows the main page instead of the report form.

# Checklist
- [x] I have performed a self-review of my own code
- [ ] I have added tests to cover my changes
- [x] I have considered splitting this into smaller pull requests.

### CODE REVIEW

**Comment by muhammed-mukthar** [comment]
@elijah-potter

File: packages/chrome-plugin/src/background/index.ts [hunk 1]
```diff
@@ -74,6 +74,21 @@ chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
 	return true;
 });
 
+chrome.tabs.onActivated.addListener(async ({ tabId }) => {
+	const result = await chrome.storage.local.get(['popupState', 'reportTabId']);
+	if (result.popupState?.page === 'report-error' && result.reportTabId !== tabId) {
+		await chrome.storage.local.set({ popupState: { page: 'main' } });
```
Comment (elijah-potter) [inline packages/chrome-plugin/src/background/index.ts]: Would you mind moving the get and set logic to two distinct functions. Since there's a bit of repetition, it might be better to isolate the prop drilling into something a bit better documented and reusable.

**Review by elijah-potter — CHANGES_REQUESTED** [review]
I've tested it and it works! This PR is almost ready to go, but needs just one quality-of-life tweak before it can be merged.

Thanks!

File: packages/chrome-plugin/src/background/index.ts (hunk 1 above)
Comment (muhammed-mukthar) [reply packages/chrome-plugin/src/background/index.ts]: hey @elijah-potter  i have made changes as you have said

**Review by elijah-potter — APPROVED** [review]
This looks good to me! Thanks for making those changes.
