### PR TITLE
fix(#2216): consider words in user dictionary to be of the user dialect for wasm

### LINKED ISSUE #2216: Incorrect flagging personal dictionary word as misspelled
**What got flagged?**
The word "Aeon" was flagged as a spelling mistake, with Harper trying to urge me to change it to Aron, Avon, and Eon.

**Why is this incorrect?**
This is incorrect since I had already marked the word into my personal dictionary, and any further attempts to add it to my dictionary does nothing, removing and readding does nothing to address the issue either.

**Example of correct usage:**
Correct usage should allow the name to be said in dialogue: "Aeon was walking." or just "Aeon."

``` data.json
"userDictionary": [
    "Aeon",
    "Trepalidaritation"
],
```

Image

### PR DESCRIPTION
**Pull request by grantlemons**
# Issues 
Closes #2216

# Description
Consider words added to the user dictionary to be of the user's dialect in the WASM client.
This allows the dialect flags to be merged by `MergedDictionary::get_word_metadata`.

We may want to consider changing `WordMetadata::default` to have all dialect flags set.

This change was already implemented in #1922 for harper-ls, but never got done for the WASM client.

# How Has This Been Tested?
Added a test in `harper-wasm/src/lib.rs`.

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have added tests to cover my changes

### CODE REVIEW

File: harper-wasm/src/lib.rs [hunk 1]
```diff
@@ -131,7 +132,7 @@ impl Linter {
         let mut lint_dict = MergedDictionary::new();
 
         lint_dict.add_dictionary(FstDictionary::curated());
-        lint_dict.add_dictionary(Arc::new(user_dictionary.clone()));
```
Comment (grantlemons) [inline harper-wasm/src/lib.rs:134]: I feel like clippy should have caught this @elijah-potter.

Comment (elijah-potter) [reply harper-wasm/src/lib.rs:134]: I agree. Is there an existing [clippy lint](https://rust-lang.github.io/rust-clippy/master/index.html?search=clone) that we need to enable?

Comment (grantlemons) [reply harper-wasm/src/lib.rs:134]: based on this issue, I guess not
https://github.com/rust-lang/rust-clippy/issues/12455

**Review by elijah-potter — APPROVED** [review]
