### PR TITLE
Closed Compound Matcher Conversions

### LINKED ISSUE #440: feat: Flag words wrongly split where the parts each happen to also be words
There's a whole bunch of words in this class and I've been noticing this kind of mistake more and more lately. I'll try to come back and add more such words as I spot them in the wild. For now I'll start with one:

- ... and you **some how** have to implement the body of the goto statement → ... and you **somehow** have to implement the body of the goto statement

My browser actually catches this one: 
Image

I'll maintain a list here, either as I remember them, or spot them in the wild:
- in tact → intact
- every where → everywhere
- surely a misleading **thumb nail** → surely a misleading **thumbnail**
- As Brit, you're not going to **up set** me → As Brit, you're not going to **upset** me

### PR DESCRIPTION
**Pull request by elijah-potter**
This continues work on #472 by defining a macro to be used to create rules that condense valid words into closed compound words. This may close #440.

If there are any additions, let me know. The current list is in `harper-core/src/linting/closed_compounds` around line 60.

### CODE REVIEW

File: harper-core/src/linting/closed_compounds.rs [hunk 1]
```diff
@@ -82,12 +82,94 @@ create_closed_compound_linter!(Northeastern, "north eastern", "northeastern");
 create_closed_compound_linter!(Upholstery, "up holstery", "upholstery");
 create_closed_compound_linter!(Proofread, "proof read", "proofread");
 
+create_closed_compound_linter!(Forever, "for ever", "forever");
+create_closed_compound_linter!(Into, "in to", "into");
```
Comment (hippietrail) [inline harper-core/src/linting/closed_compounds.rs:86]: "in to" is not always wrong. Mostly when "in" is part of a phrasal verb or "to" is part of an infinitive verb.

File: harper-core/src/linting/closed_compounds.rs [hunk 2]
```diff
@@ -82,12 +82,94 @@ create_closed_compound_linter!(Northeastern, "north eastern", "northeastern");
...
+create_closed_compound_linter!(Everyone, "every one", "everyone");
```
Comment (hippietrail) [inline harper-core/src/linting/closed_compounds.rs:87]: "every one" is not always a mistake. Especially when followed by "of".

File: harper-core/src/linting/closed_compounds.rs [hunk 3]
```diff
@@ -82,12 +82,94 @@ create_closed_compound_linter!(Northeastern, "north eastern", "northeastern");
...
+create_closed_compound_linter!(Nobody, "no body", "nobody");
+create_closed_compound_linter!(Somebody, "some body", "somebody");
+create_closed_compound_linter!(Anybody, "any body", "anybody");
+create_closed_compound_linter!(Nothing, "no thing", "nothing");
+create_closed_compound_linter!(Anyway, "any way", "anyway");
+create_closed_compound_linter!(Anytime, "any time", "anytime");
```
Comment (hippietrail) [inline harper-core/src/linting/closed_compounds.rs:93]: "anytime" is the mistake, it's just become extremely common recently. "any time" is always correct.

File: harper-core/src/linting/closed_compounds.rs [hunk 4]
```diff
@@ -82,12 +82,94 @@ create_closed_compound_linter!(Northeastern, "north eastern", "northeastern");
...
 create_closed_compound_linter!(Proofread, "proof read", "proofread");
 
+create_closed_compound_linter!(Forever, "for ever", "forever");
+create_closed_compound_linter!(Into, "in to", "into");
+create_closed_compound_linter!(Everyone, "every one", "everyone");
+create_closed_compound_linter!(Nobody, "no body", "nobody");
+create_closed_compound_linter!(Somebody, "some body", "somebody");
+create_closed_compound_linter!(Anybody, "any body", "anybody");
+create_closed_compound_linter!(Nothing, "no thing", "nothing");
+create_closed_compound_linter!(Anyway, "any way", "anyway");
```
Comment (hippietrail) [inline harper-core/src/linting/closed_compounds.rs:92]: "any way" and "anyway" are both correct but have different meanings any way you slice it.

File: harper-core/src/linting/closed_compounds.rs [hunk 5]
```diff
@@ -82,12 +82,94 @@ create_closed_compound_linter!(Northeastern, "north eastern", "northeastern");
...
+create_closed_compound_linter!(Anywhere, "any where", "anywhere");
+create_closed_compound_linter!(Nowhere, "no where", "nowhere");
+create_closed_compound_linter!(Everywhere, "every where", "everywhere");
+create_closed_compound_linter!(Overnight, "over night", "overnight");
+create_closed_compound_linter!(Instead, "in stead", "instead");
+create_closed_compound_linter!(Backpack, "back pack", "backpack");
+create_closed_compound_linter!(Cupboard, "cup board", "cupboard");
+create_closed_compound_linter!(Keyboard, "key board", "keyboard");
+create_closed_compound_linter!(Somewhere, "some where", "somewhere");
+create_closed_compound_linter!(Notebook, "note book", "notebook");
```
Comment (hippietrail) [inline harper-core/src/linting/closed_compounds.rs:103]: "note book" are equal variants for the book sense but it's never been used for the laptop sense.

File: harper-core/src/linting/closed_compounds.rs [hunk 6]
```diff
@@ -82,12 +82,94 @@ create_closed_compound_linter!(Northeastern, "north eastern", "northeastern");
...
+create_closed_compound_linter!(Middleware, "middle ware", "middleware");
+create_closed_compound_linter!(Firmware, "firm ware", "firmware");
+create_closed_compound_linter!(Smartwatch, "smart watch", "smartwatch");
+create_closed_compound_linter!(Touchscreen, "touch screen", "touchscreen");
+create_closed_compound_linter!(Headset, "head set", "headset");
+create_closed_compound_linter!(Framework, "frame work", "framework");
+create_closed_compound_linter!(Touchpad, "touch pad", "touchpad");
+create_closed_compound_linter!(Microprocessor, "micro processor", "microprocessor");
+create_closed_compound_linter!(Datacenter, "data center", "datacenter");
```
Comment (hippietrail) [inline harper-core/src/linting/closed_compounds.rs:112]: "data center" and "data centre" are equally acceptable.

File: harper-core/src/linting/closed_compounds.rs [hunk 7]
```diff
@@ -82,12 +82,94 @@ create_closed_compound_linter!(Northeastern, "north eastern", "northeastern");
...
+create_closed_compound_linter!(Smartphone, "smart phone", "smartphone");
+create_closed_compound_linter!(Webcam, "web cam", "webcam");
+create_closed_compound_linter!(Headphone, "head phone", "headphone");
+create_closed_compound_linter!(Desktop, "desk top", "desktop");
+create_closed_compound_linter!(Laptop, "lap top", "laptop");
+create_closed_compound_linter!(Overclocking, "over clocking", "overclocking");
+create_closed_compound_linter!(Backplane, "back plane", "backplane");
+create_closed_compound_linter!(Smartcard, "smart card", "smartcard");
+create_closed_compound_linter!(Bitrate, "bit rate", "bitrate");
```
Comment (hippietrail) [inline harper-core/src/linting/closed_compounds.rs:121]: "bit rate" and "bitrate" are equally acceptable.

File: harper-core/src/linting/closed_compounds.rs [hunk 8]
```diff
@@ -82,12 +82,94 @@ create_closed_compound_linter!(Northeastern, "north eastern", "northeastern");
...
+create_closed_compound_linter!(Overload, "over load", "overload");
+create_closed_compound_linter!(Underclock, "under clock", "underclock");
+create_closed_compound_linter!(Blockchain, "block chain", "blockchain");
+create_closed_compound_linter!(Opensource, "open source", "opensource");
```
Comment (hippietrail) [inline harper-core/src/linting/closed_compounds.rs:125]: "open source" is preferred over "opensource" which even my browser flags. 
image

**Comment by elijah-potter** [comment]
@hippietrail, I've taken a more data-driven approach for nouns. Let me know what you think.

File: harper-core/src/linting/closed_compounds.rs [hunk 9]
```diff
@@ -0,0 +1,342 @@
...
+                    $correct,
+                    "`."
+                )
+            }
+        }
+    };
+}
+
+create_closed_compound_linter!(Itself, "it self", "itself");
+create_closed_compound_linter!(Tonight, "to night", "tonight");
```
Comment (hippietrail) [inline harper-core/src/linting/closed_compounds.rs:57]: "to night" is too common to flag: "turning day to night", "can be like day compared to night", "the grassy field gives way to farmland and the day to night, and still you walk", "lots of people having fun from morning to night." - all on github

File: harper-core/src/linting/closed_compounds.rs [hunk 10]
```diff
@@ -0,0 +1,342 @@
...
+create_closed_compound_linter!(Myself, "my self", "myself");
+create_closed_compound_linter!(Therefore, "there fore", "therefore");
+create_closed_compound_linter!(Misunderstand, "miss understand", "misunderstand");
+create_closed_compound_linter!(Misunderstood, "miss understood", "misunderstood");
+create_closed_compound_linter!(Misuse, "miss use", "misuse");
+create_closed_compound_linter!(Misused, "miss used", "misused");
+create_closed_compound_linter!(Postpone, "post pone", "postpone");
+create_closed_compound_linter!(Worldwide, "world wide", "worldwide");
+create_closed_compound_linter!(Overall, "over all", "overall");
+create_closed_compound_linter!(Likewise, "like wise", "likewise");
```
Comment (hippietrail) [inline harper-core/src/linting/closed_compounds.rs:67]: This is not always an error, "like wise men", "like wise old owls", etc. The browser can distinguish: 
image

File: harper-core/src/linting/closed_compounds.rs [hunk 11]
```diff
@@ -0,0 +1,342 @@
...
+create_closed_compound_linter!(However, "how ever", "however");
+create_closed_compound_linter!(Altogether, "all together", "altogether");
```
Comment (hippietrail) [inline harper-core/src/linting/closed_compounds.rs:69]: Both are correct: Altogether means “completely,” “all things considered,” or “on the whole.” All together means “everyone together” or “everything together.” If we're going to suggest "are you sure you didn't mean ..." for one, we should do it for both.

File: harper-core/src/linting/closed_compounds.rs [hunk 12]
```diff
@@ -0,0 +1,342 @@
...
+create_closed_compound_linter!(Asleep, "a sleep", "asleep");
```
Comment (hippietrail) [inline harper-core/src/linting/closed_compounds.rs:70]: Both are legit. "I'm going to have a sleep after lunch" is the same as "take a nap".

File: harper-core/src/linting/closed_compounds.rs [hunk 13]
```diff
@@ -0,0 +1,342 @@
...
+create_closed_compound_linter!(Upset, "up set", "upset");
+create_closed_compound_linter!(Intact, "in tact", "intact");
```
Comment (hippietrail) [inline harper-core/src/linting/closed_compounds.rs:72]: This one really annoys the hell out of me (-: When "tact" is a noun I can't think of it coming after any preposition other than "with", so no ambiguity here (-:

File: harper-core/src/linting/closed_compounds.rs [hunk 14]
```diff
@@ -0,0 +1,342 @@
...
+create_closed_compound_linter!(Somehow, "some how", "somehow");
+create_closed_compound_linter!(Proofread, "proof read", "proofread");
+create_closed_compound_linter!(Nobody, "no body", "nobody");
```
Comment (hippietrail) [inline harper-core/src/linting/closed_compounds.rs:75]: Both are legit. Your hair can have no body, a character or creature can be just a head with no body. Browser can distinguish: 
image

File: harper-core/src/linting/closed_compounds.rs [hunk 15]
```diff
@@ -0,0 +1,342 @@
...
+create_closed_compound_linter!(Somebody, "some body", "somebody");
+create_closed_compound_linter!(Anybody, "any body", "anybody");
```
Comment (hippietrail) [inline harper-core/src/linting/closed_compounds.rs:77]: "some body" and "any body" can both be used correctly but it's probably rare. Then again in the context of programming: "I can find the function declaration but I don't see any body". Browser is surprisingly able to distinguish - impressive!
image

File: harper-core/src/linting/closed_compounds.rs [hunk 16]
```diff
@@ -0,0 +1,342 @@
...
+create_closed_compound_linter!(Nothing, "no thing", "nothing");
+create_closed_compound_linter!(Anywhere, "any where", "anywhere");
+create_closed_compound_linter!(Instead, "in stead", "instead");
+create_closed_compound_linter!(Somewhere, "some where", "somewhere");
+create_closed_compound_linter!(Middleware, "middle ware", "middleware");
+create_closed_compound_linter!(Into, "in to", "into");
```
Comment (hippietrail) [inline harper-core/src/linting/closed_compounds.rs:83]: Both are legit. As Grammarly apparently says: “Into” is a preposition that shows what something is within or inside. As separate words, in and to sometimes simply wind up next to each other.

File: harper-core/src/linting/closed_compounds.rs [hunk 17]
```diff
@@ -0,0 +1,342 @@
...
+create_closed_compound_linter!(Overclocking, "over clocking", "overclocking");
+create_closed_compound_linter!(Backplane, "back plane", "backplane");
+create_closed_compound_linter!(Overload, "over load", "overload");
+create_closed_compound_linter!(Underclock, "under clock", "underclock");
+create_closed_compound_linter!(Devops, "dev ops", "devops");
+create_closed_compound_linter!(Multithreading, "multi threading", "multithreading");
+create_closed_compound_linter!(Everywhere, "every where", "everywhere");
+create_closed_compound_linter!(Multicore, "multi core", "multicore");
+create_closed_compound_linter!(Multimedia, "multi media", "multimedia");
+create_closed_compound_linter!(Ecommerce, "e commerce", "ecommerce");
```
Comment (hippietrail) [inline harper-core/src/linting/closed_compounds.rs:93]: Neither are correct. "e-commerce" is correct.

File: harper-core/src/linting/closed_compounds.rs [hunk 18]
```diff
@@ -0,0 +1,342 @@
...
+create_closed_compound_linter!(Widespread, "wide spread", "widespread");
+create_closed_compound_linter!(Notwithstanding, "not with standing", "notwithstanding");
+create_closed_compound_linter!(Anyhow, "any how", "anyhow");
+create_closed_compound_linter!(Nonetheless, "none the less", "nonetheless");
+create_closed_compound_linter!(Hereafter, "here after", "hereafter");
```
Comment (hippietrail) [inline harper-core/src/linting/closed_compounds.rs:98]: Both are legit and in this case the former is more common: "I'll still be here after work", "I'll meet you here after work", etc. I would probably flag "hereafter".

File: harper-core/src/linting/closed_compounds.rs [hunk 19]
```diff
@@ -0,0 +1,342 @@
...
+create_closed_compound_linter!(Otherwise, "other wise", "otherwise");
```
Comment (hippietrail) [inline harper-core/src/linting/closed_compounds.rs:99]: "Other wise men may disagree". Other wise it is an error sometimes.
image

File: harper-core/src/linting/closed_compounds.rs [hunk 20]
```diff
@@ -0,0 +1,342 @@
...
+create_closed_compound_linter!(Therein, "there in", "therein");
```
Comment (hippietrail) [inline harper-core/src/linting/closed_compounds.rs:100]: The former is both legit and more common than the latter: "It's over there in that box". "I see him there in the window", etc. There in lies the problem.
image

File: harper-core/src/linting/closed_compounds.rs [hunk 21]
```diff
@@ -0,0 +1,342 @@
...
+create_closed_compound_linter!(Thereupon, "there upon", "thereupon");
+create_closed_compound_linter!(Hereby, "here by", "hereby");
```
Comment (hippietrail) [inline harper-core/src/linting/closed_compounds.rs:102]: Both legit: I here by state that I got here by way of the "issues" link.
image

File: harper-core/src/linting/closed_compounds.rs [hunk 22]
```diff
@@ -0,0 +1,342 @@
...
+create_closed_compound_linter!(Hereunder, "here under", "hereunder");
+create_closed_compound_linter!(Forthwith, "forth with", "forthwith");
```
Comment (hippietrail) [inline harper-core/src/linting/closed_compounds.rs:104]: Can occur in coding context: In my day we had to code in Forth with a line editor!

File: harper-core/src/linting/closed_compounds.rs [hunk 23]
```diff
@@ -0,0 +1,342 @@
...
+create_closed_compound_linter!(Widespread, "wide spread", "widespread");
+create_closed_compound_linter!(Notwithstanding, "not with standing", "notwithstanding");
+create_closed_compound_linter!(Anyhow, "any how", "anyhow");
+create_closed_compound_linter!(Nonetheless, "none the less", "nonetheless");
+create_closed_compound_linter!(Hereafter, "here after", "hereafter");
+create_closed_compound_linter!(Otherwise, "other wise", "otherwise");
+create_closed_compound_linter!(Therein, "there in", "therein");
+create_closed_compound_linter!(Thereupon, "there upon", "thereupon");
+create_closed_compound_linter!(Hereby, "here by", "hereby");
+create_closed_compound_linter!(Hereunder, "here under", "hereunder");
```
Comment (hippietrail) [inline harper-core/src/linting/closed_compounds.rs:103]: "It's hidden right here under the carpet".

File: harper-core/src/linting/closed_compounds.rs [hunk 24]
```diff
@@ -0,0 +1,342 @@
...
+create_closed_compound_linter!(Forthwith, "forth with", "forthwith");
+create_closed_compound_linter!(Insofar, "in so far", "insofar");
+create_closed_compound_linter!(Whereupon, "where upon", "whereupon");
+create_closed_compound_linter!(Thereafter, "there after", "thereafter");
```
Comment (hippietrail) [inline harper-core/src/linting/closed_compounds.rs:107]: "I got there after him". "Go back there after dinner and finish it." etc. Much more common than the legalese.

File: harper-core/src/linting/closed_compounds.rs [hunk 25]
```diff
@@ -0,0 +1,342 @@
...
+create_closed_compound_linter!(Downright, "down right", "downright");
```
Comment (hippietrail) [inline harper-core/src/linting/closed_compounds.rs:108]: "We've gotta do down right here" etc.

**Comment by ccoVeille** [comment]
All the counter examples that @hippietrail gave are extremely valuable.

They should be added in a non-regression tests that will be a global one and not directly linked to this rule.

Someone in the future may be tempted to open a PR to fix anything listed by @hippietrail as valid.

**Comment by elijah-potter** [comment]
> They should be added in a non-regression tests that will be a global one and not directly linked to this rule.

I absolutely agree. I added them to the global tests, which actually revealed some issues. They've since been fixed.

File: harper-core/affixes.json [hunk 26]
```diff
@@ -633,6 +633,15 @@
...
+    },
+    "j": {
+      "suffix": true,
+      "cross_product": true,
+      "replacements": [],
+      "adds_metadata": {},
+      "gifts_metadata": {
+        "adverb": {}
+      }
     }
```
Comment (ccoVeille) [inline harper-core/affixes.json:645]: This, no?

```suggestion
    "j": {
      "#": "adverb",
      "suffix": true,
      "cross_product": true,
      "replacements": [],
      "adds_metadata": {},
      "gifts_metadata": {
        "adverb": true
      }
     }
```

Comment (ccoVeille) [reply harper-core/affixes.json]: I suggested adding #, but also to fix `adverb: {}` with `adverb: true`

File: harper-core/affixes.json [hunk 27]
```diff
@@ -633,6 +633,16 @@
...
       }
+    },
+    "j": {
+      "#": "adverb property",
+      "suffix": true,
+      "cross_product": true,
+      "replacements": [],
+      "adds_metadata": {},
+      "gifts_metadata": {
+        "adverb": {}
```
Comment (ccoVeille) [inline harper-core/affixes.json:644]: All others are like this


```suggestion
        "adverb": true
```

Previously reported here

https://github.com/Automattic/harper/pull/608#discussion_r1949814237

Comment (ccoVeille) [reply harper-core/affixes.json:644]: @elijah-potter you merged apparently

Comment (elijah-potter) [reply harper-core/affixes.json:644]: Ah, no. The `{}` is intentional.

Comment (ccoVeille) [reply harper-core/affixes.json:644]: OK thanks
