### PR TITLE
fix(core): fix `AnA` false-positives

### LINKED ISSUE #2406: AnA false positives, mostly acronyms
**What got flagged?**

Trying out AnA on https://github.com/home-assistant/home-assistant.io/tree/current/source/_integrations flagged a bunch of false positives, categorized below.

All uppercase acronym cases

- a UDP connection
- a UPB device 
- a UPS or power device
- a USB 2.0 port
- an HEVC HLS stream

Other acronymish ones

- an FFmpeg-compatible input file
- an [mDNS](https://en.wikipedia.org/wiki/Multicast_DNS) tool
- an RFLink device
- a [udev](https://en.wikipedia.org/wiki/Udev) rule

Other cases

- a Honeywell alarm panel
- a OneDrive folder
- a Ubiquiti UniFi Network application

**Why is this incorrect?**

Per pronounciation.

**Example of correct usage:**

N/A, above list should be accepted (+ flagged if the _other_ a/an is incorrectly used).

### LINKED ISSUE #2525: False positive: `AnA` flags "a USB" → "an USB"
Image

"An" is used before words starting with a vowel sound. The sound of "USB" is "you ess bee", starting with a consonant. As such "A USB" is correct and "An USB" is wrong.

### PR DESCRIPTION
**Pull request by 86xsk**
# Issues 

Fixes #2525
Fixes #2406 

# Description

Fixes some reported false-positives in `AnA`.

To simplify the handling of empty words, I've made `starts_with_vowel` return `Option<InitialSound>`. I'm not sure if that's the best idea, or if it might be better to return `InitialSound::Either` for empty words instead. The latter would help reduce code noise somewhat, since we wouldn't need all the `Some()` and the unwrapping wherever the function is called.

# How Has This Been Tested?

- `cargo test`

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have added tests to cover my changes

### CODE REVIEW

File: harper-core/src/char_string.rs [hunk 1]
```diff
@@ -3,9 +3,12 @@ use std::borrow::Cow;
 
 use smallvec::SmallVec;
 
+// TODO: remove this when `SmallVec` allows retrieving this value in a const context.
```
Comment (elijah-potter) [inline harper-core/src/char_string.rs:6]: That would be sweet!
